theme: jekyll-theme-minimal
title: Samir Jain
description: Samir Jain's software projects
linkedin: https://www.linkedin.com/in/samirjain93/
email: sjsamphex@gmail.com
logo: ./images/Samir-Banner.jpg
